<Project Sdk="Aspire.AppHost.Sdk/13.3.5">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>6df418dd-6a8f-4191-8c70-e2f55d0d1fcd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.5" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.3.5" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.3.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Booking.API\Booking.API.csproj" />
    <ProjectReference Include="..\Cinema.API\Cinema.API.csproj" />
    <ProjectReference Include="..\Gateway\Gateway.csproj" />
    <ProjectReference Include="..\Identity.API\Identity.API.csproj" />
    <ProjectReference Include="..\Movie.API\Movie.API.csproj" />
    <ProjectReference Include="..\Payment.API\Payment.API.csproj" />
  </ItemGroup>

</Project>
